layout_spectrum: 0.4189497370230458
typography_spectrum: 0.710770431945543
color:
  brandStrength: 0.026333647374211268
  lightness: 0.6096751974393051
  saturation: 0.977631824713772
  rhythmicContrast: 0.0021151689153238395
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
name: UNLEASH YOUR BEAST - The Retreat
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: whats that
    id: 397eccad-c8d5-49a1-b6ed-ca7c27399374
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a93483d-672e-4c7a-abad-d38495b4ddbb.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a93483d-672e-4c7a-abad-d38495b4ddbb.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: contact
    url: 'mailto:info@michaelstief.de'
    label: Contact me
content_rating:
  adult: false
logo: null
title: Unleash your Beast - THE RETREAT
description: Mentoring & Coaching with Michael Stief
github: true
author:
  name: Michael Stief
  email: info@maternity-photography-workshops.com
